/*  =========================================================================
    zproject_pg_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZPROJECT_PG_CLASSES_H_INCLUDED
#define ZPROJECT_PG_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/zproject_pg.h"

//  Extra headers

//  Opaque class structures to allow forward references

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef ZPROJECT_PG_BUILD_DRAFT_API

//  Self test for private classes
ZPROJECT_PG_PRIVATE void
    zproject_pg_private_selftest (bool verbose, const char *subtest);

#endif // ZPROJECT_PG_BUILD_DRAFT_API

#endif
